Pba 4830
brightcove-archive/ooyala_native-skin pull request #515
Opened 2017-01-10 19:38 UTC by pcaseooyala

Added support for specifying accentColor in skin.json.  Accent color is already supported on the web app.  It is used to specify color for the toggle thumb (iOS only - not supported on Android), volume control and buttons.  The accent color value will override a hard-coded value.

2017-01-10 22:02 UTC, lental requested changes

2017-01-10 22:02 UTC, lental commented on sdk/react/panels/languageSelectionPanel.js
> +  getThumbTintColor: function() {
hey is this used?

2017-01-10 22:02 UTC, lental commented on sdk/react/progressBar.js
> +      var playedColor = this.props.config.controlBar.adScrubberBar.playedColor ? this.props.config.controlBar.adScrubberBar.playedColor : this.props.config.general.accentColor;
this should have a condition if neither exist

2017-01-10 22:02 UTC, lental commented on sdk/react/controlBar.js
> +    } else {
can we add a condition here if neither exists?

2017-01-10 22:43 UTC, pcaseooyala commented on sdk/react/panels/languageSelectionPanel.js
> +  getThumbTintColor: function() {
No - will remove

2017-01-10 22:43 UTC, pcaseooyala commented on sdk/react/controlBar.js
> +    } else {
What do we do if neither exists?

2017-01-10 23:14 UTC, pcaseooyala commented on sdk/react/progressBar.js
> +      var playedColor = this.props.config.controlBar.adScrubberBar.playedColor ? this.props.config.controlBar.adScrubberBar.playedColor : this.props.config.general.accentColor;
Ok, will set to a default value if neither exist

2017-01-10 23:15 UTC, pcaseooyala commented on sdk/react/controlBar.js
> +    } else {
Will set to a default value if neither exist

2017-01-11 00:12 UTC, pcaseooyala commented
Investigate:
 more options icons
 control bar icons
 play/pause

Should these be colored?

2017-01-11 00:13 UTC, pcaseooyala commented
Volume control bar - right now both sides of the bar are colored.  See if only the left side should be oolored.

2017-01-11 00:14 UTC, lental commented on sdk/react/controlBar.js
> +  /**
white space

2017-01-11 00:31 UTC, pcaseooyala commented
Suggestion: instead of changing the toggle thumb color, change the toggle background color.  The problem is that currently the toggle background is blue, and then changing the thumb color (from white) makes the resulting toggle look really bad.

2017-01-11 00:35 UTC, pcaseooyala commented
On iOS, the scrubber bar is not showing on the left side.  Investigate to see if we introduced a bug.

2017-01-26 20:05 UTC, lental commented
are there still changes to be added for this?

2017-01-26 20:08 UTC, pcaseooyala commented
Let me check again with Jeoffrey.  I didn't hear back from him earlier.

2017-01-26 21:51 UTC, mistermendez commented
hey @pcaseooyala let's sync up to review outstanding UI accent color changes

2017-01-26 22:01 UTC, mistermendez commented
@pcaseooyala here are some test links you can use to compare web accent color to native:
* https://goo.gl/IKbtQp (blue accent color)
* https://goo.gl/1N8lCc (red accent color)

2017-01-26 22:05 UTC, mistermendez commented
For web toggle switch, we change the switch background color, not the switch thumb color -

![screen shot 2017-01-26 at 2 02 12 pm](https://cloud.githubusercontent.com/assets/3091495/22352234/2af53054-e3d0-11e6-8fbf-70663c38748f.png)

2017-01-26 22:13 UTC, mistermendez commented
For web we do not apply accent color to control bar buttons, play/pause, or more options buttons.

The only time accent color is used for buttons is to indicate an active popover on desktop. Native does not have popovers so this won't apply to native-skin.

![screen shot 2017-01-26 at 2 07 09 pm 2](https://cloud.githubusercontent.com/assets/3091495/22352430/fae69f00-e3d0-11e6-8437-b52ce022adb8.png)

2017-01-27 18:25 UTC, mistermendez commented on sdk/react/controlBar.js
> +        return '#4389FF';
should we add these colors to constants.js?

2017-01-27 18:25 UTC, mistermendez commented on sdk/react/progressBar.js
>          return '#FF3F80';
should we add these colors to constants.js?

2017-01-27 18:26 UTC, mistermendez commented on sdk/react/progressBar.js
>          return '#4389FF';
should we add these colors to constants.js?

2017-01-27 21:29 UTC, pcaseooyala commented on sdk/react/progressBar.js
>          return '#4389FF';
This is an excellent idea, and it will be covered by a separate Jira issue.

2017-01-27 21:51 UTC, merged