[PLAYER-2243]
brightcove-archive/ooyala_native-skin pull request #604
Opened 2017-11-29 15:41 UTC by atopilskii

Add set seek time to 0 if there is negative value

2017-11-29 15:54 UTC, AlinaVoronkovaEpam requested changes

2017-11-29 15:54 UTC, AlinaVoronkovaEpam commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinLayoutController.java
> +        }
Use smth like this: `= Math.max(0, ..)` instead of `if(timeAfterSeek < 0) { ...`

2017-11-30 11:14 UTC, AlinaVoronkovaEpam approved these changes

2017-12-04 10:04 UTC, IvanSakharovskii approved these changes

2017-12-04 10:04 UTC, merged