[PLAYER-1724] Advanced Player Controls
brightcove-archive/ooyala_native-skin pull request #742
Opened 2018-08-29 15:30 UTC by AlinaVoronkovaEpam

[PLAYER-3712] Playback-rate: Communication between skin and sdk.

Please merge sdk and skin branches simultaneously.

2018-08-30 00:06 UTC, pilievOoyala commented
LGTM

2018-08-30 15:57 UTC, SZadorozhnyiEpam commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinBridgeEventHandlerImpl.java
> +    Dynamic dynamic = parameters.getDynamic("playbackSpeedRate");
Can it be extracted as a static string?

2018-08-30 15:59 UTC, SZadorozhnyiEpam requested changes
Left a comment

2018-08-30 15:59 UTC, SZadorozhnyiEpam commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinBridgeEventHandlerImpl.java
> +    Dynamic dynamic = parameters.getDynamic("playbackSpeedRate");
Can it be extracted as static field?

2018-08-30 16:17 UTC, akshaydch11 commented
As this feature is targeted for 4.40 and 4.39 is small release so we don't want to take chances of introducing new bugs by merging this into candidate. So, lets hold off merging till we release 4.39.

2018-08-31 14:29 UTC, AlinaVoronkovaEpam commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinBridgeEventHandlerImpl.java
> +    Dynamic dynamic = parameters.getDynamic("playbackSpeedRate");
done

2018-09-03 09:16 UTC, SZadorozhnyiEpam approved these changes

2018-09-17 19:33 UTC, brol1dev reviewed
I added one comment. I think I'm going to merge the PR to create a RC but please fix and also what I commented in android-sdk repo.

2018-09-17 19:33 UTC, rcvrgs commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinBridgeEventHandlerImpl.java
> +    _player.setSelectedPlaybackSpeed(Float.parseFloat(speed));
use `OoyalaPlayer.setPlaybackSpeed(float)` instead now and we can remove `setSelectedPlaybackSpeed`

2018-09-17 22:28 UTC, brol1dev approved these changes
LGTM

2018-09-17 23:18 UTC, merged