[PLAYER-4134] Replay icon
brightcove-archive/ooyala_native-skin pull request #747
Opened 2018-09-04 20:47 UTC by cacel

[iOS][Android][OoyalaSkinSampleApp] Replay icon is displayed on seeking back after end of video and play instead replay from sec 0.

2018-09-04 20:49 UTC, brol1dev requested changes
There's a conflict in the PR, please fix.

2018-09-04 20:59 UTC, pilievOoyala commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinBridgeEventHandlerImpl.java
> +    _player.seek(0);
Is this enough?  What happens to ads? Do they replay using this method?

2018-09-04 21:00 UTC, rcvrgs commented
@cacel also there's a related issue that we just merged a fix (#745) Can you check that one out too and see how different it is? I'm not sure if there's a difference or if the tickets are actual duplicates.

2018-09-04 21:03 UTC, cacel commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinBridgeEventHandlerImpl.java
> +    _player.seek(0);
The seek is set to 0. The ads will shown but without adMode (same behavior in web).

2018-09-04 21:07 UTC, cacel commented
@rcvrgs Both tickets are similar. Basically when the video is finished (with ads or without them) and after scrubbing, the button replay starts from where you finished to scrub. 
This PR, when the endScreen is shown and the user uses the scrubber bar and clicks replay button, the content will start from the beginning.

2018-09-18 22:55 UTC, akshaydch11 approved these changes

2018-09-18 23:33 UTC, pilievOoyala commented
@rcvrgs Can you re-review?  I will address the issue about replay in a separate thread.

2018-10-24 10:10 UTC, DmitriiMaslov commented
@cacel do we need to move it to DEV branch? @SergeyBicarte  @bychkovdmitry @orobles-ooyala  Please review

2019-03-11 15:08 UTC, closed without merging

2019-03-11 15:09 UTC, DmitriiMaslov commented
The related ticket marked as done. PR is too old to merge it into Candidate so I am closing it.