[PLAYER-4004] Fix for misaligned Player Control bar
brightcove-archive/ooyala_native-skin pull request #755
Opened 2018-09-21 10:38 UTC by SergeyBicarte

Added correct calculation for size of OoyalaSkinLayout for all cases (toggle full screen/orientation changing)

2018-09-21 15:41 UTC, ZadorozhnyiSemen commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinLayout.java
> +      layoutParams.height = displayMetrics.heightPixels-statusBarHeight;
Just missing spaces around `-`. Everything else looks good

2018-09-21 15:42 UTC, ZadorozhnyiSemen requested changes

2018-09-21 15:42 UTC, ZadorozhnyiSemen commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinLayout.java
> +      layoutParams.height = displayMetrics.heightPixels-statusBarHeight;
Just missing spaces around `-`. Everything else looks good

2018-09-24 10:30 UTC, SergeyBicarte commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinLayout.java
> +      layoutParams.height = displayMetrics.heightPixels-statusBarHeight;
Done

2018-09-24 17:33 UTC, brol1dev approved these changes
not quite sure if it will work but we can give it a try.

2018-09-24 17:33 UTC, rcvrgs commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinLayout.java
> -        sourceWidth = layoutParams.width;
do you no longer need the sourceWidth and height? Remember we needed it to know the original width and height before going into fullscreen mode.

2018-09-24 17:34 UTC, rcvrgs commented
however this fix is for the next release (4.41) so holding the merge until we release the current one.

2018-09-28 10:30 UTC, SergeyBicarte commented
I am changed that fix, no need size calculation at all, just added forceLayout() calls at point when size really changed (after orientation changing and after hide/show bars), this also fixing  [PLAYER-3034](https://jira.corp.ooyala.com:8443/browse/PLAYER-3034)

2018-10-01 08:21 UTC, SZadorozhnyiEpam approved these changes

2018-10-01 08:29 UTC, merged