[Player 4652] [Android][VRSampleApp] Fullscreen doesn't work
brightcove-archive/ooyala_native-skin pull request #770
Opened 2018-11-02 10:57 UTC by SergeyBicarte

This fix have two parts. First one is for android , it's introduce back saving/restoring original (started) size of layout. Second one is for  React Native, it's seems style "flex": 1 is not working correctly in some conditions for main react native view (as result, some times, that view have wrong size), i propose setting sizes in style with "width" and "height" attribs.

2018-11-06 12:26 UTC, isheftel-ooyala requested changes

2018-11-06 12:26 UTC, isheftel-ooyala commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinLayout.java
> +    void onFrameChangeCallback(int width, int height,int prevWidth,int prevHeight);
code style here, spaces between arguments

2018-11-06 12:26 UTC, isheftel-ooyala commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinLayout.java
> +
redundant new  line

2018-11-06 12:26 UTC, isheftel-ooyala commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinLayout.java
> +  protected void onAttachedToWindow () {
code style

2018-11-06 13:52 UTC, SergeyBicarte commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinLayout.java
> +    void onFrameChangeCallback(int width, int height,int prevWidth,int prevHeight);
Done

2018-11-06 13:52 UTC, SergeyBicarte commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinLayout.java
> +
Done

2018-11-06 13:52 UTC, SergeyBicarte commented on sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaSkinLayout.java
> +  protected void onAttachedToWindow () {
Done

2018-11-07 07:06 UTC, isheftel-ooyala approved these changes
LGTM

2018-11-07 11:54 UTC, bychkovdmitry approved these changes
LGTM

2018-11-07 12:10 UTC, merged