[Player 3037] Mute Behavior in iOS (App)
brightcove-archive/ooyala_native-skin pull request #773
Opened 2018-11-10 10:00 UTC by grigory9

_OOAudioSession_ prioritizes on __OOSkinViewController::toggleFullscreen_ event

2018-11-10 10:15 UTC, maxkupetskii requested changes

2018-11-10 10:15 UTC, maxkupetskii commented on sdk/iOS/OoyalaSkinSDK/ViewControllers/OOSkinViewController.m
> +      [[OOAudioSession sharedInstance] prioritize];
Use dot syntax to access properties

2018-11-10 10:15 UTC, maxkupetskii commented on sdk/iOS/OoyalaSkinSDK/ViewControllers/OOSkinViewController.m
> +@import OoyalaSDK;
Place this import before any `#import`

2018-11-10 11:27 UTC, grigory9 commented on sdk/iOS/OoyalaSkinSDK/ViewControllers/OOSkinViewController.m
> +      [[OOAudioSession sharedInstance] prioritize];
Thanks, Fixed

2018-11-10 11:27 UTC, grigory9 commented on sdk/iOS/OoyalaSkinSDK/ViewControllers/OOSkinViewController.m
> +@import OoyalaSDK;
Thanks, Fixed

2018-11-13 18:26 UTC, brol1dev commented on sdk/iOS/OoyalaSkinSDK/ViewControllers/OOSkinViewController.m
> +@import OoyalaSDK;
wasn't aware of this syntax. Why using `@import OoyalaSDK` and not `#import <OoyalaSDK/OoyalaSDK.h>`?

2018-11-14 14:16 UTC, grigory9 commented on sdk/iOS/OoyalaSkinSDK/ViewControllers/OOSkinViewController.m
> +@import OoyalaSDK;
Module importing is more durable, fast and modern approach then Headers importing

2018-11-19 10:40 UTC, grigory9 commented on sdk/iOS/OoyalaSkinSDK/ViewControllers/OOSkinViewController.m
> +@import OoyalaSDK;
Reverted back

2018-11-19 15:41 UTC, MarkEPAM approved these changes

2018-11-19 15:41 UTC, MarkEPAM commented on sdk/iOS/OoyalaSkinSDK/ViewControllers/OOSkinViewController.m
> +    bool fullscreen = !self.fullscreen;
use `BOOL` instead of `bool`

2018-11-19 15:42 UTC, merged