[PLAYER-4925_4926] Fixed buttons on seekend
brightcove-archive/ooyala_native-skin pull request #798
Opened 2018-12-18 09:47 UTC by isheftel-ooyala

Fixed rewind and skip buttons behavior according to this acceptance criterias:
https://jira.corp.ooyala.com/browse/PLAYER-4925
https://jira.corp.ooyala.com/browse/PLAYER-4926

2018-12-18 12:23 UTC, MarkEPAM requested changes
On iOS skip controls don't work after the replay state, also `replay` button does't change icon to `playing` after the same state

2018-12-18 12:28 UTC, isheftel-ooyala commented
Why such  a difference on different platforms, on Android everything works fine only after this changes.
And before these changes problems were only on Android.
Maybe check for platform, what do you think?

2018-12-24 12:02 UTC, maxkupetskii approved these changes

2018-12-24 14:41 UTC, SergeyBicarte approved these changes
LGTM

2018-12-24 14:50 UTC, merged