[PLAYER-5181] Chromecast list screen created
brightcove-archive/ooyala_native-skin pull request #841
Opened 2019-02-11 15:34 UTC by isheftel-ooyala

Chromecast list screen created

2019-02-11 16:01 UTC, SergeyBicarte approved these changes
LGTM

2019-02-11 16:11 UTC, atopilskii commented on sdk/react/ooyalaSkinPanelRenderer.js
> +        moreDetailsScreen: this.skin.props.moreOptionsScreen,
Why do we use this "moreOptionsScreen" for cast button?

2019-02-11 16:14 UTC, atopilskii requested changes

2019-02-11 16:14 UTC, atopilskii commented on sdk/react/panels/CastDevicesScreen.js
> +      this.props.config.moreDetailsScreen.color,
The same thing: i think it is necessery to use new color for Cast. What do you think?

2019-02-11 16:14 UTC, atopilskii commented on sdk/react/panels/CastDevicesScreen.js
> +      this.props.config.moreDetailsScreen.color,
and here

2019-02-11 16:14 UTC, atopilskii commented on sdk/react/ooyalaSkinPanelRenderer.js
> +        moreDetailsScreen: this.skin.props.moreOptionsScreen,
Why do we use this "moreOptionsScreen" for cast button?

2019-02-11 18:30 UTC, isheftel-ooyala reviewed
@atopilskii 
created separate cast options https://github.com/ooyala/android-sample-apps/pull/430

PR is updated, now we use colors from options in active and inactive states

2019-02-12 12:34 UTC, atopilskii approved these changes

2019-02-12 12:51 UTC, merged